export type AuthUser = {
  id: string;
  name: string;
  email: string;
  avatarInitial: string;
  avatarUrl: string | null;
  onboardingCompleted: boolean;
  favoriteCategories: string[];
  cityId: string | null;
  city: string | null;
  slug: string | null;
  bio: string | null;
  verified: boolean;
  swapsCount: number;
  ratingAvg: number;
  ratingCount: number;
  createdAt: string | null;
  showCompletedListings: boolean;
  hidePersonalData: boolean;
};
